Updates to web
dltxio/dltxio.github.io pull request #86
Opened 2021-09-30 05:24 UTC by JasminFarhi

Added Mesh photos
Added careers page and apply
Added updates to agile principals

2021-09-30 23:35 UTC, xiangzhe0812 approved these changes

2021-09-30 23:36 UTC, xiangzhe0812 commented
just neet format few pages like careers.html

2021-10-01 01:03 UTC, Mitchell139 requested changes
What's the point of the "theMesh.md"? Right now it's empty

2021-10-01 01:03 UTC, Mitchell139 commented on theMesh.html
> +                                         Alex Xiang <br>
Formatting

2021-10-01 01:03 UTC, Mitchell139 commented on theMesh.html
> +                                          <img src="../dltxio.github.io/images/The-Mesh/Mitchel-Westmoreland.jpg" alt="">
That's not how you spell my name

2021-10-01 01:03 UTC, Mitchell139 commented on theMesh.html
> +                                          <img src="../dltxio.github.io/images/The-Mesh/Rob Braunack.jpg" alt="">
Missing hyphen

2021-10-01 06:10 UTC, bitcoinbrisbane commented on theMesh.html
> +                                          <img src="../dltxio.github.io/images/The-Mesh/Mitchel-Westmoreland.jpg" alt="">
lol

2021-10-01 06:12 UTC, bitcoinbrisbane commented on theMesh.html
> +                                          <img src="../dltxio.github.io/images/The-Mesh/Mitchel-Westmoreland.jpg" alt="">
Fixed

2021-10-01 06:12 UTC, bitcoinbrisbane commented on theMesh.html
> +                                          <img src="../dltxio.github.io/images/The-Mesh/Rob Braunack.jpg" alt="">
Fixed.

2021-10-01 06:16 UTC, bitcoinbrisbane commented on theMesh.html
> +                                         Alex Xiang <br>
Fixed

2021-10-02 03:47 UTC, bitcoinbrisbane commented on careers.html
> +                      <img src="../dltxio.github.io/images/icons/web-development.png" alt="">
Fixed

2021-10-02 03:47 UTC, bitcoinbrisbane commented on careers.html
> +</body>
Fixed

2021-10-02 03:47 UTC, bitcoinbrisbane approved these changes

2021-10-02 03:48 UTC, merged